source 'https://rubygems.org'
gem 'nokogiri'
gem 'rack', '~> 2.2.4'
gem 'rspec'
gem "webrick", "~> 1.9"
# gem "jekyll"
# gem "jekyll-theme-minimal"
# gem "kramdown"
gem "github-pages", "~> 232", group: :jekyll_plugins